version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c '
      npm install -g cnpm --registry=https://registry.npm.taobao.org &&
      cnpm install &&
      cnpm install -g nodemon &&
      nodemon -w server/ server/app.js
      '
    ports:
      - "8080:8080"
    networks:
      - all

networks:
  all:
