version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # command: sh -c 'npm install; npm install -g nodemon; nodemon app.js'
    # nodemon for server restart on code changes & webpack-dev-server to serve client modules
    command: >
      sh -c '
      npm install &&
      npm install -g nodemon &&
      nodemon -w server/ server/app.js
      '

    ports:
      - "80:3000"
    networks:
      - all
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/dockerdemo"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
