version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon; nodemon app.js'
    ports:
      - "80:3000"
    networks:
      - all

networks:
  all:
