version: '2'
services:

  web:
    build:
      context: .
      dockerfile: dockerfile_dev
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c '
      npm install &&
      nodemon -w server/ server/server.js
      '
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - all
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/stockdb"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
