version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c '
      npm install &&
      npm install -g webpack webpack-dev-server &&
      npm install -g nodemon &&
      nodemon -w server/ server/app.js
      '
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - all

networks:
  all:
